development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: project_school_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: project_school_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: project_school_production
  pool: 5
  username: root
  host: localhost