DatabaseCleaner.clean_with(:truncation)

School.create(:name=>"Dummy School 1", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890")
School.create(:name=>"Dummy School 2", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890")

Subject.create(:name=>"Dummy Subject 1", :school_id=>1)
Subject.create(:name=>"Dummy Subject 2", :school_id=>1)
Subject.create(:name=>"Dummy Subject 3", :school_id=>2)
Subject.create(:name=>"Dummy Subject 4", :school_id=>2)
Subject.create(:name=>"Dummy Subject 5", :school_id=>2)
Subject.create(:name=>"Dummy Subject 6", :school_id=>2)

Classroom.create(:name=>"Dummy Classroom 1", :no_of_students=>10, :school_id=>1, :subject_ids=>["1"])
Classroom.create(:name=>"Dummy Classroom 2", :no_of_students=>10, :school_id=>1, :subject_ids=>["1","2"])
Classroom.create(:name=>"Dummy Classroom 3", :no_of_students=>10, :school_id=>2, :subject_ids=>["3","6"])
Classroom.create(:name=>"Dummy Classroom 4", :no_of_students=>10, :school_id=>2, :subject_ids=>["5","4"])
Classroom.create(:name=>"Dummy Classroom 5", :no_of_students=>10, :school_id=>2, :subject_ids=>["3","4","5"])

Student.create(:name=>"Dummy Student 1", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"1" ,:classroom_id=>"1" ,:subject_ids=>["1"])
Student.create(:name=>"Dummy Student 2", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"1" ,:classroom_id=>"2" ,:subject_ids=>["1","2"])
Student.create(:name=>"Dummy Student 3", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"1" ,:classroom_id=>"2" ,:subject_ids=>["1","2"])
Student.create(:name=>"Dummy Student 4", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"2" ,:classroom_id=>"3" ,:subject_ids=>["3","6"])
Student.create(:name=>"Dummy Student 5", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"2" ,:classroom_id=>"3" ,:subject_ids=>["3","6"])
Student.create(:name=>"Dummy Student 6", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"2" ,:classroom_id=>"3" ,:subject_ids=>["6"])
Student.create(:name=>"Dummy Student 7", :father_name=>"Dummy Father", :mother_name=>"Dummy Mother", :address=>"Dummy Address", :city=>"Dummy City", :state=>"Dummy State", :zipcode=>"123456", :phone=>"1234567890", :school_id=>"2" ,:classroom_id=>"5" ,:subject_ids=>["3","4","5"])

Teacher.create(:name=>"Dummy Teacher 1", :gender=>"Male", :phone=>"1234567890", :school_id=>"1", :classroom_ids=>["1","2"], :subject_ids=>["1","2"])
Teacher.create(:name=>"Dummy Teacher 2", :gender=>"Male", :phone=>"1234567890", :school_id=>"1", :classroom_ids=>["1"], :subject_ids=>["1"])
Teacher.create(:name=>"Dummy Teacher 3", :gender=>"Male", :phone=>"1234567890", :school_id=>"2", :classroom_ids=>["3","5"], :subject_ids=>["3","4"])
Teacher.create(:name=>"Dummy Teacher 4", :gender=>"Male", :phone=>"1234567890", :school_id=>"2", :classroom_ids=>["3","4","5"], :subject_ids=>["5","6","3"])
Teacher.create(:name=>"Dummy Teacher 5", :gender=>"Male", :phone=>"1234567890", :school_id=>"2", :classroom_ids=>["4","5"], :subject_ids=>["4"])